#!/bin/sh
# from ethan schoonover
# https://github.com/altercation/dotfiles-tilingwm/blob/c9c6684381215a865116523868790eeae7e4fd2f/bin/wm/status-net

dev_wifi=wlp3s0
# dev_eth=enp0s31f6 
dev_vpn=tun0

# colors from ulysses theme
bg_d=#220F23
bg_l=#461437
foreground=#C1D8E8
red_d=#AD1F1D
red_l=#D0281D 
green_d=#93AB53
green_l=#CFDFB2
yellow_d=#DB8F31
yellow_l=#EAC628
blue_d=#1F509C
blue_l=#467BBF
pink_d=#BB497A
pink_l=#DE72A4
violet_d=#8A64AF
violet_l=#AB88C0
white_d=#C1D8E8
white_l=#F5F8EF


# connectivity status
# states are:
# none (no connectivity)
# portal (behind captive portal)
# limited (connected to network but no internet access)
# full (full internet connectivity)
# unknown

std_color=$violet_l
wifi_icon=""

connectivity="$(nmcli networking connectivity)"

case $connectivity in
    none)
        color=$red_d
        connectivity_w_icon=" $connectivity "
        icon=" " ;; # f056 fa-minus-circle 
    portal)
        color=$yellow_d
        connectivity_w_icon=" $connectivity "
        icon=" " ;; # f05c fa-times-circle-o
    limited)
        color=$yellow_d
        connectivity_w_icon=" $connectivity "
        icon=" " ;; # f01b fa-arrow-circle-o-up 
    full)
        color=$std_color
        connectivity_w_icon=""
        icon="" ;; # icon="" ;; # f0aa fa-arrow-circle-up 
    *)
        color=$red_d
        connectivity_w_icon=" $connectivity "
        icon=" " ;; # f29c fa-question-circle-o
esac

# ethernet stuff !?
# eth="$(ip -o address | grep -i "$dev_eth *inet ")"
# if [ -n "$eth" ]
# then
#     #eth="${eth##*inet }"
#     speed="$(cat /sys/class/net/$dev_eth/speed)"
#     case $speed in
#         10) speed="10Base-T" ;;
#         100) speed="100Base-T" ;;
#         1000) speed="Gigabit" ;;
#         *) speed="UNKNOWN $speed" ;;
#     esac
#     #eth_status="  $speed ${eth%%/*}"
#     eth_status="  $speed"
# fi

ssid="$(iw dev $dev_wifi link | grep -i SSID)"
if [ -n "$ssid" ]
then
    signal="$(iw dev $dev_wifi station dump | egrep '[^ ]signal avg')"
    signal="${signal#*-}"
    signal="${signal%% *}"
    signal="$((2*(100-signal)))"
        
#    if   ((signal < 20))
#    then
#        sigicon="⠀"
#    elif ((signal < 40))
#    then
#        sigicon="⣀"
#    elif ((signal < 60))
#    then
#        sigicon="⣤"
#    elif ((signal < 80))
#    then
#        sigicon="⣶"
#    else
#        sigicon="⣿"
#    fi
    # signal=$((signal/5*5)) # get rid of some jitter
    ((signal > 100)) && signal=100
    ((signal < 100)) && signal=" $signal"
    #    ▁ ▂ ▃ ▄ ▅ ▆ ▇ █
    wifi_status="$wifi_icon ${signal}% ${ssid##*SSID: }"
#    if [ -n "$eth" ]
#    then
#        wifi_ip="$(ip -o address | grep -i "$dev_wifi *inet ")"
#        wifi_ip=" ${wifi_ip##*inet }"
#        wifi_status="$wifi_status${wifi_ip%%/*}"
#    fi
fi

# vpn stuff?!
vpn="$(ip -o address | grep -i "$dev_vpn *inet ")"
if [ -n "$vpn" ]
then
    #vpn="${vpn##*inet }"
    #vpn_status=" ${vpn%%/*}"
    vpn_status=" "
    color=$green
else
#    vpn_status=" "
    vpn_status=""
fi

# echo "<fc=$color>${vpn_status}$icon${connectivity##*full}$wifi_status$eth_status</fc>"
echo "<fc=$color>${vpn_status}$connectivity_w_icon$wifi_status$eth_status</fc>"

# vim: ft=sh:expandtab:ts=4:shiftwidth=4
