#! /bin/bash

#darkorlight="$HOME/.config/xcolors/dark-or-light"
#
#if [ -f $darkorlight ] && [ $(head -1 $darkorlight) == "dark" ]
#then
#    echo "changing to light scheme" 
#    echo "light" > $darkorlight
#    python $HOME/bin/colour-manager.py light-scheme
#
#else
#    echo "changing to dark scheme"
#    echo "dark" > $darkorlight
#    python $HOME/bin/colour-manager.py dark-scheme
#
#fi

darkmode="$HOME/.config/darkmode"

if [ -e $darkmode ]
then
    rm $darkmode
    $(rm $HOME/.config/kitty/kittycolours.conf)
    $(ln -s $HOME/.config/kitty/light.conf $HOME/.config/kitty/kittycolours.conf)
    if [ "$(pgrep kitty)" ]
    then
        $(kitty @ --to=unix:/tmp/mykitty set-colors --all --configured $HOME/.config/kitty/kitty.conf)
    fi
    python $HOME/.scripts/colour-manager.py light-scheme
else
    touch $darkmode
    $(rm $HOME/.config/kitty/kittycolours.conf)
    $(ln -s $HOME/.config/kitty/dark.conf $HOME/.config/kitty/kittycolours.conf)
    if [ "$(pgrep kitty)" ]
    then
        $(kitty @ --to=unix:/tmp/mykitty set-colors --all --configured $HOME/.config/kitty/kitty.conf)
    fi
    python $HOME/.scripts/colour-manager.py dark-scheme
fi

$HOME/.scripts/refresh-colours
